use std::ptr::write_volatile;

// ============================================
// COMPILE-TIME OBFUSCATION ENGINE
// ============================================

/// XOR obfuscate string at compile time
#[macro_export]
macro_rules! obf_str {
  ($s:expr, $key:expr) => {{
    const LEN: usize = $s.len();
    const OBF: [u8; LEN] = {
      let bytes = $s.as_bytes();
      let mut out = [0u8; LEN];
      let mut i = 0;
      while i < LEN {
          out[i] = bytes[i] ^ $key;
          i += 1;
      }
      out
    };
    OBF
  }};
}

// Stack-only deobfuscation with zeroization
pub struct SecretBuf<const N: usize> {
  pub buf: [u8; N],
  pub len: usize,
}

impl<const N: usize> SecretBuf<N> {
  pub fn deobf_from_hex(hex: &[u8], key: u8) -> Self {
    let mut deobf = [0u8; N];

    // The resulting string length is half the hex string length
    let target_len = hex.len() / 2;
    let len = target_len.min(N);

    for i in 0..len {
        // Grab exactly 2 bytes for the hex pair
        if let Ok(hex_str) = std::str::from_utf8(&hex[i*2 .. i*2+2]) {
            if let Ok(byte_val) = u8::from_str_radix(hex_str, 16) {
                deobf[i] = byte_val ^ key;
            }
        }
    }

    SecretBuf { buf: deobf, len }
  }

  /// Decode raw XOR obfuscated bytes generated by `obf_str!`
  pub fn deobf(bytes: &[u8; N], key: u8) -> Self {
      let mut deobf = [0u8; N];
      // Prevent out of bounds if the string is longer than the buffer N
      let len = bytes.len().min(N);

      for i in 0..len {
          deobf[i] = bytes[i] ^ key;
      }

      SecretBuf { buf: deobf, len }
  }

  pub fn as_str(&self) -> &str {
      std::str::from_utf8(&self.buf[..self.len])
          .expect("Invalid UTF-8 after deobfuscation")
  }

}
impl<const N: usize> Drop for SecretBuf<N> {
  fn drop(&mut self) {
    // Use volatile writes to prevent the compiler from optimizing the wipe away
    for i in 0..N {
      unsafe { write_volatile(&mut self.buf[i], 0) };
    }
    self.len = 0;
  }
}